ajout des docs
lbo462/starflit pull request #116
Opened 2024-06-28 09:27 UTC by BAAAL00

2024-06-28 09:30 UTC, lbo462 requested changes

2024-06-28 09:30 UTC, lbo462 commented on docs/5_ContinuingTheProject.md
> +[Check this documentation](7_UngoingWork.md#mapping)
**ON**going work

2024-06-28 09:30 UTC, lbo462 commented on docs/5_ContinuingTheProject.md
> +[Check this documentation](7_UngoingWork.md##Fine-tuning-with-Pytorch)
**ON**going work

2024-06-28 09:31 UTC, lbo462 commented on docs/5_ContinuingTheProject.md
> +[Check this documentation](7_UngoingWork.md##Fine-tuning-with-Pytorch)
+ header links are broken

2024-06-28 09:31 UTC, lbo462 commented on docs/5_ContinuingTheProject.md
> +[Check this documentation](7_UngoingWork.md#mapping)
+ header links are broken

2024-06-28 09:49 UTC, lbo462 requested changes

2024-06-28 09:49 UTC, lbo462 commented on docs/7_OngoingWork.md
> +# Transfer learning and fine-tuning
Main title doesn't match the file name ... The displayed name in Doxygen won't be the one expected.
The main title should be `Ongoing work` and this title should be h2

2024-06-28 09:49 UTC, lbo462 commented on docs/7_OngoingWork.md
> +During the last days of the project, we manage to finetune MobileNetv3Large with pytorch. After getting the finetuned model, we managed to make it run on the Raspberry Pi.
managed

2024-06-28 09:49 UTC, lbo462 commented on docs/7_OngoingWork.md
> +The objective of this part of the project, is to use a model tht already exist, and to use it's already intelligent structure to use it to do something else.
that

2024-06-28 09:49 UTC, lbo462 commented on docs/7_OngoingWork.md
> +First, you will have to download the script files that are in `misc/finetuning/finetuning.py` on the repo on the machine you want to do the training. They might be :  [here](https://www.youtube.com/w
You says _files_ at plural but you point to a single file.
You should point to `misc/finetuning/`

2024-06-28 09:49 UTC, lbo462 commented on docs/7_OngoingWork.md
> +Once you have enjoyed downloading them, you will have to create a virtual environnement :
downloading ? They're on the repo, the one reading this just cloned them

2024-06-28 09:49 UTC, lbo462 commented on docs/7_OngoingWork.md
> +nohup python3 finetuning.py > training.log &
Say that this will create a detached process, killable with the `kill` command, and that the output is in `nohup.out`. Or just link to this man : https://linux.die.net/man/1/nohup

2024-06-28 09:49 UTC, lbo462 commented on docs/7_OngoingWork.md
> +At the end of the training, you will have a .pth file : this is your fine tuned model.
No space before `:` in english

2024-06-28 09:49 UTC, lbo462 commented on docs/7_OngoingWork.md
> +Once it's done, you can download the script files that are in `misc/finetuning/objectRecognition.py` on the repo, and start the script (assuming you configured correctly your Raspberry Pi).
Still plural but pointing to a single file

2024-06-28 09:49 UTC, lbo462 commented on docs/7_OngoingWork.md
> +I would advise that you don't rely too much on the scripts that were made. There were just POCs, and can be largely improved.
Here, link to the official doc here https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html

2024-06-28 09:49 UTC, lbo462 commented on docs/7_OngoingWork.md
> +You might already have heard of _fine-tuning_ to train a pre-existing model
All of this doesn't belong here and should be moved to the head of the file

2024-06-28 09:49 UTC, lbo462 commented on docs/7_OngoingWork.md
> +### Starflit's transfer learning objectives
Same for this

2024-06-28 09:49 UTC, lbo462 commented on misc/finetuning/finetuning.py
> +import os
Add a comment explaining what this file is

2024-06-28 09:49 UTC, lbo462 commented on misc/finetuning/objectRecognition.py
> +import torch
Same here

2024-06-28 10:01 UTC, MarsiaSec commented on docs/7_OngoingWork.md
> +In brief, transfer learning is:
this list is weird

2024-07-07 16:06 UTC, lbo462 approved these changes

2024-07-07 16:12 UTC, merged