18 ajouter un code led pour chaque action
lbo462/starflit pull request #82
Opened 2024-06-21 08:14 UTC by MarsiaSec

2024-06-21 16:20 UTC, lbo462 requested changes

2024-06-21 16:20 UTC, lbo462 commented on arduino/main/src/Leds.h
> +         *
You can remove this line

2024-06-21 16:20 UTC, lbo462 commented on arduino/main/src/RescueBot.h
> +        //void leds();
If you do not use this, you can remove it

2024-06-21 16:20 UTC, lbo462 commented on docs/DevEnv.md
> +You will also need to update the `includePath` by adding the path the `c_cpp_properties.json` file:
You might* also need [...]
On Linux, even with a fresh installation without the Arduino IDE, I didn't need to do that.

Plus, you didn't say where to put this file. Is this a VSCode config ?

2024-06-21 16:20 UTC, lbo462 commented on docs/DevEnv.md
> +> **NEED TO CHECK IF IT WORKS CORRECTLY**
Thus, should we put this on master now ?
Are we sure of this ?

2024-06-21 16:30 UTC, lbo462 requested changes

2024-06-21 16:30 UTC, lbo462 commented on arduino/main/src/Leds.cpp
> +        if (ledIsOn == 0)
You can just do `if(ledIsOn)` since it's a boolean

2024-06-21 16:30 UTC, lbo462 commented on arduino/main/src/Leds.cpp
> +        if (ledIsOn == 0)
Same here

2024-06-21 16:30 UTC, lbo462 commented on arduino/main/src/Leds.cpp
> +                // TEST:
Test this or remove it

2024-06-26 15:48 UTC, lbo462 requested changes

2024-06-26 15:48 UTC, lbo462 commented on arduino/main/src/RescueBot.h
> +        bool objectDetected = false;
Changed this with selfFound and otherFound (or something like it) to make it clearer

2024-06-26 15:48 UTC, lbo462 commented on arduino/main/src/RescueBot.h
> +        const int ledPin=2, numLeds=33, brightness=50;
Should be here

2024-06-26 15:48 UTC, lbo462 commented on arduino/main/src/RescueBot.cpp
> +        //delay(10000);
Remove this

2024-06-26 15:48 UTC, lbo462 commented on arduino/main/src/RescueBot.cpp
> +    if(!RPIInitialized)
Why ? You should stop the motors if you found something too

2024-06-26 15:48 UTC, lbo462 commented on arduino/main/src/RescueBot.cpp
> +    ledStrip.setup();
Duplicated

2024-06-26 15:48 UTC, lbo462 commented on arduino/main/src/Leds.h
> +        Colors colors[4] = {
Shouldn't this be outside of the class too ?

2024-06-27 07:09 UTC, lbo462 commented on arduino/main/src/RescueBot.h
> +        const int ledPin=2, numLeds=33, brightness=50;
Should not*

2024-06-27 08:04 UTC, MarsiaSec reviewed
ok

2024-06-27 08:14 UTC, lbo462 approved these changes

2024-06-27 08:14 UTC, merged