SystemD and RPI install
lbo462/starflit pull request #90
Opened 2024-06-25 11:05 UTC by lbo462

2024-06-25 11:07 UTC, lbo462 commented on python/setup.sh
> +source /opt/starflit/starflit/python/venv/bin/activate
Instead of using source, maybe one could directly use the location of pip in the venv, it would be safer

2024-06-25 11:07 UTC, lbo462 commented on python/setup.sh
> +pip install -r /opt/starflit/starflit/python/requirements.txt
See above comment.
Replace `pip` by `/opt/starflit/starflit/python/venv/bin/pip`

2024-06-25 11:07 UTC, lbo462 commented on python/setup.sh
> +mv /opt/starflit/starflit/python/default.env /opt/starflit/starflit.python/.env
cp instead of mv would be better

2024-06-26 13:55 UTC, MarsiaSec requested changes

2024-06-26 13:55 UTC, MarsiaSec commented on docs/0_GettingStarted.md
> +it for GitHub with curl.
from

2024-06-26 13:55 UTC, MarsiaSec commented on raspberry/install.sh
> +#   It installs all the necessary component to control
components

2024-06-26 13:55 UTC, MarsiaSec commented on raspberry/install.sh
> +#   It also install the systemD so that the python
installs

2024-06-26 13:55 UTC, MarsiaSec commented on raspberry/install.sh
> +#   script that exhanges data with the Arduino gets
exchanges

2024-06-26 13:55 UTC, MarsiaSec commented on raspberry/install.sh
> +#   It also install the systemD so that the python
systemd :)

2024-06-26 13:56 UTC, MarsiaSec approved these changes

2024-06-26 13:57 UTC, lbo462 commented
No Docker in sight, but a fresh install script !

2024-06-26 15:30 UTC, merged